Repository RNNLA/Scrapper, pull requests merged in 2023-08, with the labels that each got.

#1 Create news_format.json
  news_format.json
Labels: data

#2 Ants patched
  news_format.json
Labels: data

#3 Template for the common function
  requirements.txt
  src/parse.py
Labels: enhancement

#6 leave selector only & 2nd news format
  news_format.json
Labels: data

#8 Update news_format.json
  news_format.json
Labels: data

#9 Add template for PULL Requeust
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#12 Add regex sub & Update missed params
  requirements.txt
  src/parse.py
Labels: enhancement

#14 Adapted google pylint
  pylintrc
  src/parse.py
Labels: documentation, enhancement

#13 Link get function
  .gitignore
  requirements.txt
  src/link_getter.py
Labels: enhancement

#16 Common function
  pylintrc
  requirements.txt
  src/parse.py
Labels: enhancement

#17 Link get function
  .gitignore
  requirements.txt
  src/link_getter.py
Labels: enhancement
